### ISSUE TITLE
WebExtension Developers Alliance

### ISSUE THREAD

**Issue by ImprovedTube** [avi12/web-ext-deploy#3]
hi there =)   whats your discord?  it is very impressive that you published 20+ projects,  and distributed in different channels.  

(are you using ImprovedTube? / making this extension https://github.com/code4charity/YouTube-Extension)

it is so sad to see that little extensions,  more often than not, won't surpass a few 1000 users or don't serve a unique purpose, don't make the developer happy, won't be maintained in 5 or 10 years.  
At the same time Open-Source could be so much more efficient ( https://github.com/code4charity/Open-Source-Bot--Github-Pull-Request-Bot--Auto-Git-Contributor/blob/main/README.md )     
(And in our niche, for example, even awesome projects with 100,000 users just resigned their maintenance eventually. example:  https://github.com/YePpHa/YouTubeCenter & iridium) 

Let's say right now there might be only less than 50 people in the world, who work on youtube extensions as much and seriously  as you do.  -  Then  why don't many of them team up?  (Any benefit in this "diversity? Fragmentation of efforts. a single developer who has a good amount of users might work more happily/motivated than several who each have few users. so competition can be unneccessary(/preventing one perfect/flawless result)   

And the most striking(unique) work isn't done yet. (Let alone maintenance duties secured for long).    
We have 150+ feature requests waiting. And there are other projects, with more purposes pockettube, sponsorblock, https://github.com/Eugene-Gubar/YCS , etc.)   
(And we look forward to pass on donations(if any)
And when providing a feature as a standalone extension, it would sometimes be more fun (/efficient/'educational) than re-developing, to add a build-script to a package (like ImprovedTube), copying/scraping that feature's code. (upwards compatible. saving maintenance hassles) And so on,..., ..._

👋Curious what you think!👋   (just wrote this, might move some of this content to our /discussions or readme later)

**Comment by avi12** [comment]
Hey, it's cool that I'm starting to get recognized by extensions with large user bases!
Teaming up sounds very cool! How do you see us teaming up?

**Comment by ImprovedTube** [comment]
hey :) 
 ### teaming _(/volunteering)_
 trying to know people & understand. Won't guess today what will be the best next effort for you/somebody to try today. Just the obvious conclusion: Synergy (through being more unique/less repetitive as a group than alone) - More positive impact _(, more reputation, more potential compensation [generally, contributors of big/combined projects could remain equally independent / exclusive licences/prominent mentions/link of credits/...])  
 ##### Extension developers are not just playing/practicing   
taking the zoomed-out pespective feels strange/sad as said. I.e. why would several volunteers, who want to do good in the world and possibly volunteer/donate much of their time, do work on the same goal/feature, each alone.  (And without a competitive reason or financial fear even (but they just dont talk? are introverts?).   Obviously you and us (and X more people) have resilience to keep on working. Yet no maintenance in X years should be mandatory, for your/our contributions to remain benefitial. I guess that's a reason you choose Open source. Yet even a repo with 3000 stars is not a guarantee to be continued the day that the main author leaves)_    In theory ImprovedTube should auto charge just a few cents per user, to ensure muuch more development. Same for unique/appreciated single feature projects.  Yet solutions like brave browser are still small so it still might require a long breath (and wont be very competitive then either, if ever)

####  compare: 
there is only one current Version of Wikipedia. (For example) the Wikipedia article about Youtube for has 50000 daily readers, 3200 watchers, 85000 characters, 4000 previous editors and about 0 competitiors.  ImprovedTube, should be more similar in metrics(?) (more editors).  Despite Improvedtube has a long history it is not selfsustaining and wont get easier to maintain for free/alone.  So obviously it is not our greatest dream to be strong in this niche like this. We are just willing to take the responsiblity. 

So question of the day: how to make people starting now, consider to work together rather than alone?   

#### VS.  "Partnerships":  
assuming we'd value full independence/"decentral power" extremely, than likely 200 extension operators with 20000 users each might still be better for example (no single point of failture),  than one charity association serving 4million users.
But in case many of the same points apply. I.e. the 200 developers should sync have a common ToDo list? andp rojects should still checkout each other? we should simply place links to some extension in our menu, that fullfil some of our missing features/enhanced settings, so we dont have to work on them. Resulting in for example 5000 or 10000 installations per year(depending what feature) and probably you could send as many users to ImprovedTube somehow. Both of which could enhance/grow all products, since both links can be meaningful.

**Comment by ImprovedTube** [comment]
hey :) 
 ### teaming _(/volunteering)_
 trying to know people & understand. Won't guess today what will be the best next effort for you/somebody to try today. Just the obvious conclusion: Synergy (through being more unique/less repetitive as a group than alone) - More positive impact (,  _more reputation, more potential compensation [generally, contributors of big/combined projects could remain equally independent / exclusive licences/prominent mentions/link of credits/...]_)  
 ##### Extension developers are not just playing/practicing   
taking the zoomed-out pespective feels strange/sad as said. I.e. why would several volunteers(,_who have passion for what they do and want to do good in the world and possibly volunteer/donate much of their time_),  all do work on the same goal/feature, each alone? ( And without a competitive reason/financial fear even) - So they just dont talk? are introverts?).   Obviously you and us (and X more people) have resilience to keep on working. Yet no maintenance in X years should be mandatory, for your/our contributions to remain benefitial. I guess that's a reason you choose Open source. Yet even a repo with 3000 stars is not a guarantee to be continued the day that the main author leaves)_    In theory ImprovedTube should auto charge just a few cents per user, to ensure muuch more development. Same for unique/appreciated single feature projects.  Yet solutions like brave browser are still small so it still might require a long breath (and wont be very competitive then either, if ever)

####  compare: 
there is only one current Version of Wikipedia. (For example) the Wikipedia article about Youtube for has 50000 daily readers, 3200 watchers, 85000 characters, 4000 previous editors and about 0 competitiors.  ImprovedTube, should be more similar in metrics(?) (more editors).  Despite Improvedtube has a long history it is not selfsustaining and wont get easier to maintain for free/alone.  So obviously it is not our greatest dream to be strong in this niche like this. We are just willing to take the responsiblity. 

So question of the day: how to make people starting now, consider to work together rather than alone?   

#### VS.  "Partnerships":  
assuming we'd value full independence/"decentral power" extremely, than likely 200 extension operators with 20000 users each might still be better for example (no single point of failture),  than one charity association serving 4million users.
But in case many of the same points apply. I.e. the 200 developers should sync have a common ToDo list? andp rojects should still checkout each other? we should simply place links to some extension in our menu, that fullfil some of our missing features/enhanced settings, so we dont have to work on them. Resulting in for example 5000 or 10000 installations per year(depending what feature) and probably you could send as many users to ImprovedTube somehow. Both of which could enhance/grow all products, since both links can be meaningful.

**Comment by ImprovedTube** [comment]
hey :)  in other words:
 ### teaming _(/volunteering)_
 trying to know people & understand. Won't guess today what will be the best next effort for you/somebody to try today. Just the obvious conclusion: Synergy (through being more unique/less repetitive as a group than alone) - More positive impact (,  _more reputation, more potential compensation [generally, contributors of big/combined projects could remain equally independent / exclusive licences/prominent mentions/link of credits/...]_)  
 ##### Extension developers are not just playing/practicing   
taking the zoomed-out pespective feels strange/sad as said. I.e. why would several volunteers(,_who have passion for what they do and want to do good in the world and possibly volunteer/donate much of their time_),  all do work on the same goal/feature, each alone? ( And without a competitive reason/financial fear even) - So they just dont talk? are introverts?).   Obviously you and us (and X more people) have resilience to keep on working. Yet no maintenance in X years should be mandatory, for your/our contributions to remain benefitial. I guess that's a reason you choose Open source. Yet even a repo with 3000 stars is not a guarantee to be continued the day that the main author leaves)_    In theory ImprovedTube should auto charge just a few cents per user, to ensure muuch more development. Same for unique/appreciated single feature projects.  Yet solutions like brave browser are still small so it still might require a long breath (and wont be very competitive then either, if ever)

####  compare: 
there is only one current Version of Wikipedia. (For example) the Wikipedia article about Youtube for has 50000 daily readers, 3200 watchers, 85000 characters, 4000 previous editors and about 0 competitiors.  ImprovedTube, should be more similar in metrics(?) (more editors).  Despite Improvedtube has a long history it is not selfsustaining and wont get easier to maintain for free/alone.  So obviously it is not our greatest dream to be strong in this niche like this. We are just willing to take the responsiblity. 

So question of the day: how to make people starting now, consider to work together rather than alone?   

#### VS.  "Partnerships":  
assuming we'd value full independence/"decentral power" extremely, than 200 extension developers/owners with 20000 users each might still have advantage (no single point of failture), above for example one charity association serving 4million users.
- still in that case many of the same points apply.  I.e. the 200 developers should sync somehow and have a common ToDo list? and projects should still checkout each other? we should simply place links to some extension in our menu, that fulfil some of our missing features/enhanced settings, so we don't have to work on them. Resulting in for example 8000 installations per year(depending what feature) and probably you could send as many users to ImprovedTube somehow. Both of which could enhance/grow all products, since both links can be meaningful. 
  
 ----

 have a nice evening
