### ISSUE TITLE
[Bug] --get-cookies does nothing

### ISSUE THREAD

**Issue by icetbr** [avi12/web-ext-deploy#38]
### Describe the bug

`./node_modules/.bin/web-ext-deploy --get-cookies=firefox opera` does nothing

### How to reproduce

add to package.json
`{ "devDependencies": { "web-ext-deploy": "^0.8.3" } }`

run
`./node_modules/.bin/web-ext-deploy --get-cookies=firefox opera`

### What's the version you're running?

0.8.3

**Comment by icetbr** [comment]
Lubuntu 18.04

**Comment by icetbr** [comment]
Hmm, it's the way I'm calling the executable. Disabling the isUseCli check works.

https://github.com/avi12/web-ext-deploy/blob/13535239d44328a63742281e5c00fd871ed69038/src/index.ts#L50

**Comment by avi12** [comment]
What value does `process.argv` in 
https://github.com/avi12/web-ext-deploy/blob/13535239d44328a63742281e5c00fd871ed69038/src/index.ts#L12
have?

**Comment by avi12** [comment]
This is why it didn't work, because it didn't match the RegExp

**Comment by avi12** [comment]
Pushed version [0.8.4](https://github.com/avi12/web-ext-deploy/releases/tag/0.8.4), lemme know if it works now

**Comment by icetbr** [comment]
It did, thank you!
