### ISSUE TITLE
Seeing 429 response for "too many requests"

### ISSUE THREAD

**Issue by pviswanathan** [avi12/web-ext-deploy#48]
https://github.com/avi12/web-ext-deploy/blob/5c6961f677589c27b93fce725211750d12c30d17/src/stores/edge/edge-deploy.ts#L69

I tried to find API doc references to why 429's are issued with no luck. We are able to reproduce the 429 pretty consistently. Might it make sense to extend the timeout between requests to something higher?

**Comment by avi12** [comment]
You're welcome to implement an exponential backoff algorithm, test that it works and then create a PR and I'll merge it

**Comment by avi12** [comment]
Added exponential backoff in [0.13.0](../releases/tag/0.13.0)
