### ISSUE TITLE
[Bug] : latest version fails my github actions pipeline

### ISSUE THREAD

**Issue by leblancmeneses** [avi12/web-ext-deploy#49]
### Describe the bug

`
+ npx web-ext-deploy --env --publish-only=chrome
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'http-status' imported from /home/runner/.npm/_npx/b3cd4de558e681fc/node_modules/web-ext-deploy/dist-esm/stores/edge/edge-deploy.js
`

### How to reproduce

run npx web-ext-deploy --env --publish-only=chrome

### What's the version you're running?

latest pubshed

### What OS are you running it on?

ubuntu-latest

### Additional context

Reverting back to npx web-ext-deploy@0.13.4 --env --publish-only=chrome 
fixes the issue.

**Comment by avi12** [comment]
Thanks for the bug report, missed that one, fixed in 0.14.1

**Comment by avi12** [comment]
I only fixed it now because I got pinged by email about 10 minutes ago 😅
